Callable parameter fix
thecodingmachine/safe pull request #288
Opened 2021-08-15 20:49 UTC by Duroth

The generator checks for overloaded methods (functions with multiple signatures) and excludes these from the auto-generated functions.

However, this check errors on functions that include a callable in their parameters; in many cases, the callable's signature gets a synopsis of its own on the docs, which means the generator erroneously interprets it as an overloaded function.

This PR aims to fix this edge case by only pulling the synopsis from the "Description" section of the docpage, and excluding the "Parameters" part. This should mean that any synopses pertaining to the function's parameters, rather than the function itself, are now skipped and no longer trip up the generator.

2021-08-18 08:31 UTC, dbrekelmans requested changes
Thanks @Duroth! There are some removals by the generator which might or might not be related to your change. If they are not related, you can revert the removals. The build will fail, but I can still merge it and look for the root cause through a different PR.

2021-08-18 08:31 UTC, dbrekelmans commented on generated/image.php
> -function imagegrabwindow(int $handle, bool $client_area = false)
This should not have been removed: https://www.php.net/manual/en/function.imagegrabwindow

2021-08-18 08:31 UTC, dbrekelmans commented on generated/simplexml.php
> -function simplexml_import_dom(\DOMNode $node, string $class_name = SimpleXMLElement::class): \SimpleXMLElement
This file should not have been removed. If the root cause is not related to the issue you're fixing, you could manually add it back (the build will fail, but I can still merge it and look at it in a different PR)

2021-08-18 08:31 UTC, dbrekelmans commented on generated/spl.php
> -function class_implements($class, bool $autoload = true): array
This file should not have been removed

2021-08-18 08:31 UTC, dbrekelmans commented on generated/url.php
> -function get_headers(string $url, bool $associative = false, $context = null): array
This file should not have been removed

2021-08-18 08:31 UTC, dbrekelmans commented on generator/src/DocPage.php
> +        // handlers, callbacks, and other callable-type arguments, not the function itself.
Nice fix! This adds a few functions that were not generated before :+1:

2021-08-18 08:31 UTC, dbrekelmans commented on rector-migrate.php
> -            'imagegrabwindow' => 'Safe\imagegrabwindow',
Keep in mind, if you revert unjust removals to also revert those function removals in this file

2021-08-18 18:23 UTC, Duroth commented on generated/dom.php
> + * @return \DOMElement|false The DOMElement node added.
You can blame phpstan for this. ;)

2021-08-18 18:25 UTC, Duroth commented on generated/array.php
> +function array_flip($array): array
Probably due to phpstan changing the parameters; PHP-Safe borrows parameter info from phpstan, and array_flip is one of the only functions I can find that is mapped with typed arrays:

```
'array_flip' => ['array', 'input'=>'array<int|string>'],
```

Just about all other functions use a generic `array` type hint.

2021-08-18 18:56 UTC, Duroth commented
- I've reverted the `.gitignore` changes;
- I've also reverted the generated code. While this may go against contributing guidelines, the (already) failing build is a good reminder of what functions still need to be looked at. I feel there's plenty more to be done before we can confidently re-generate a new baseline source.

2021-08-19 08:25 UTC, dbrekelmans approved these changes

2021-08-19 08:26 UTC, dbrekelmans commented
Thansk @Duroth!

2021-08-19 08:27 UTC, merged