Update rector-migrate.php to support latest Rector
thecodingmachine/safe pull request #372
Opened 2022-07-25 01:24 UTC by alexandreelise

Support Rector 0.13.x features mainly RectorConfig

2022-07-25 06:25 UTC, alexandreelise commented
Hello codingmachine team I watched an old PHP talk from 2018 last night they talked about your project safe. I gave it a try following the instructions in your README but the composer require --dev rector/rector installed the latest version of rector which doesn't use the ContainerConfigurator anymore but rather their own RectorConfig. Here is the author official blog post about this change: [related blog post of Rector author](https://getrector.org/blog/new-in-rector-012-introducing-rector-config-with-autocomplete)

Thanks for your awesome work have a great day.

2022-08-04 14:08 UTC, dbrekelmans commented
Hey @alexandreelise, looks good to me! If you could fix the failing checks, then everything will be good to merge 👍

2022-08-04 15:13 UTC, alexandreelise commented
> Hey @alexandreelise, looks good to me! If you could fix the failing checks, then everything will be good to merge +1

Hey @dbrekelmans I'll look into it thanks for the feedback. Happy to help as much as I can.

2022-08-04 15:49 UTC, alexandreelise commented
Hey @dbrekelmans I just pushed the changes as you requested can you give a check please?

2022-08-04 16:21 UTC, dbrekelmans requested changes

2022-08-04 16:21 UTC, dbrekelmans commented on .gitignore
> +.idea
This is user-specific and should not be in this repo. You could add this to your local global gitignore file https://gist.github.com/subfuzion/db7f57fff2fb6998a16c
```suggestion
```

2022-08-04 16:43 UTC, alexandreelise commented on .gitignore
> +.idea
ok

2022-08-04 17:02 UTC, alexandreelise commented on .gitignore
> +.idea
Hi @dbrekelmans your suggested change was solved in https://github.com/thecodingmachine/safe/pull/372/commits/8e6f7c54be36d87451e19d0f6651a6a1936db273

2022-08-04 19:16 UTC, alexandreelise commented
I completely forgot to read the CONTIBUTING guideline. My bad. Now that I red it I followed the steps it should work as expected. Please review @dbrekelmans . Have a great day.

2022-08-05 08:40 UTC, dbrekelmans approved these changes

2022-08-05 08:40 UTC, merged

2022-08-05 08:43 UTC, alexandreelise commented
Happy to contribute. Have a great day @dbrekelmans and thecodingmachine team. Take care.